### ISSUE TITLE
error when installing package and nlmixr2

### ISSUE THREAD

**Issue by motyocska** [nlmixr2/dparser-R#20]
Hi Matt,

I was trying to reinstall nlmixr2 and getting this for dparse -12 (-11 installs nicely), am using Ubuntu:

In file included from d.h:39,
                 from rdparse.c:2:
rdparse.c: In function ‘callparsefn’:
/usr/share/R/include/Rinternals.h:882:25: warning: implicit declaration of function ‘lcons’; did you mean ‘cos’? [-Wimplicit-function-declaration]
  882 | #define LCONS(a, b)     lcons((a), (b))         /* language lists */
      |                         ^~~~~
/usr/share/R/include/Rinternals.h:984:36: note: in definition of macro ‘PROTECT’
  984 | #define PROTECT(s)      Rf_protect(s)
      |                                    ^
rdparse.c:30:19: note: in expansion of macro ‘LCONS’
   30 |   t = s = PROTECT(LCONS(R_NilValue, Rf_allocList(4)));
      |                   ^~~~~
/usr/share/R/include/Rinternals.h:882:25: warning: passing argument 1 of ‘Rf_protect’ makes pointer from integer without a cast [-Wint-conversion]
  882 | #define LCONS(a, b)     lcons((a), (b))         /* language lists */
      |                         ^~~~~~~~~~~~~~~
      |                         |
      |                         int
/usr/share/R/include/Rinternals.h:984:36: note: in definition of macro ‘PROTECT’
  984 | #define PROTECT(s)      Rf_protect(s)
      |                                    ^
rdparse.c:30:19: note: in expansion of macro ‘LCONS’
   30 |   t = s = PROTECT(LCONS(R_NilValue, Rf_allocList(4)));
      |                   ^~~~~
In file included from d.h:39,
                 from rdparse.c:2:
/usr/share/R/include/Rinternals.h:1766:17: note: expected ‘SEXP’ {aka ‘struct SEXPREC *’} but argument is of type ‘int’
 1766 | SEXP Rf_protect(SEXP);
      |                 ^~~~
In file included from d.h:39,
                 from rdparse.c:2:

I can give you more output if needed,

thanks,

Andras

**Comment by mattfidler** [comment]
Hi Andras,

To solve your problem use:

```r
remotes::install_github("nlmixr2/dparser-R")
```

I think this is because you do not use R `4.4`.

This error is because `CRAN` stated that it needed me to update to a more recent version of interacting with `R` that was no longer part of their public API.  The provided code that was supposed to work on older releases of R but for some reason doesn't on `dparser` (it does on `rxode2`).

I changed this to `#ifdef` to work for now, but I haven't had this released for 1 month yet, so I need to wait for that time to resubmit to CRAN.

The one thing I will note is depending on how `CRAN` flags this API issue, it may or may not make the CRAN release so it will be `.13` but perhaps with a different solution...

**Comment by mattfidler** [comment]
Since this is already "fixed" just waiting for the timeclock. I will close this for now.

**Comment by motyocska** [comment]
Updated successfully. Thanks Matt!
Andras

Yahoo Mail: Search, Organize, Conquer 
 
  On Sat, Oct 12, 2024 at 11:52 AM, Matthew ***@***.***> wrote:   


Since this is already "fixed" just waiting for the timeclock. I will close this for now.

**Comment by mattfidler** [comment]
Glad to hear
